# Generated by Django 3.2.11 on 2022-01-16 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf_uuid', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cowrywisecustomer',
            options={'ordering': ('-created_at',)},
        ),
    ]
